version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    command: mysqld --sql_mode="traditional" --default-authentication-plugin=mysql_native_password --log_bin_trust_function_creators=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - net

  pgsql:
    container_name: pgsql
    image: postgres:12-alpine
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=net
    ports:
      - 5432:5432
    networks:
      - net

  mongo:
    container_name: mongo
    image: mongo:4.2.3
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - net

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - net

networks:
  net:
    driver: bridge
